#!/usr/bin/env python3
"""gen_matrix.py -- conformance-matrix cart generator (z8conformance Layer 2).

Emits m_*.p8 carts that sweep the PICO-8 API surface, each self-reporting
CONFVAL/CONFHASH lines exactly like the hand-written conformance carts:
the same cart runs on the local reference PICO-8 binary (goldens, LOCAL
only -- never committed/shipped) and on z8headless (zepto8, under test);
any line difference = a zepto8 conformance bug pinned to that API group.

Coverage philosophy: games can only misbehave through engine primitives,
so pinning the primitive surface protects carts nobody has played. Each
cart packs many parameter combinations into per-group screen hashes
(coarse but exhaustive) plus targeted CONFVALs (exact values, precise
diagnosis). Risky/lexer-dependent features are isolated in their own
carts so a load failure can't mask other groups.

Usage:  python3 gen_matrix.py          (writes m_*.p8 into this directory)
Then:   regenerate goldens (gen_goldens.ps1, local) + run run_conformance.sh.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))

HEADER = """pico-8 cartridge // http://www.pico-8.com
version 42
__lua__
-- GENERATED by gen_matrix.py -- do not hand-edit (edit the generator).
-- conformance-matrix cart: emits CONFVAL/CONFHASH lines; identical output
-- on PICO-8 (-x) and z8headless = conformant.
function _rst()
 camera() clip() pal() palt() fillp(0) cls(0)
end
function _sh()
 local h=0
 for a=0x6000,0x7fff do h=bxor(rotl(h,3),@a) end
 return h
end
function _v(l,v)
 if type(v)=="number" then
  printh("CONFVAL "..l.."="..tostr(v,true))
 else
  printh("CONFVAL "..l.."="..tostr(v))
 end
end
function _s(l) _v(l,_sh()) end
"""

CARTS = {}

CARTS["m_shapes"] = """
-- basic shape primitives: sweeps incl. negative/out-of-bounds/inverted/
-- degenerate coordinates.
_rst()
local c=0
for i=-2,18 do
 rectfill(i*7-10,i*5-8,i*7+4,i*5+9,c) c=(c+1)%16
end
_s("rectfill")
_rst()
for i=-2,18 do
 rect(i*9-12,120-i*6,i*9+9,i*6-9,i%16)
end
_s("rect")
_rst()
for i=0,15 do
 line(64,64,64+cos(i/16)*80,64+sin(i/16)*80,i)
end
line(-20,-20,150,100,7) line(5,5,5,5,8) line(10,20,10,90,9) line(0,127,127,0,10)
line(20,110,40,115,11) line(60,120) line(80,100)
_s("line")
_rst()
for i=0,12 do
 circ(i*11-8,40,i,i+2)
 circfill(i*11-8,90,12-i,i+1)
end
circfill(64,64,0,7) circ(200,64,90,8) circfill(-10,-10,25,9)
_s("circ")
_rst()
for i=0,9 do
 oval(i*13-6,10+i*3,i*13+20,50-i*2,i+3)
 ovalfill(i*13,127-i*9,i*13+8+i,80,i+5)
end
_s("oval")
_rst()
for i=-5,140,7 do pset(i,abs(i)%128,i%16) end
_v("pget1",pget(0,0)) _v("pget2",pget(7,7)) _v("pgetoob",pget(-1,200))
_s("pset")
"""

CARTS["m_fillp_cam_clip"] = """
-- fill patterns (incl. transparency bit + two-color args), clip regions
-- (incl. out-of-bounds), camera offsets, and their combination.
_rst()
fillp(0x33cc)
rectfill(4,4,60,40,0x4e)
fillp(0xa5a5.8)
circfill(90,30,20,0x7d)
fillp(0x5a5a)
ovalfill(10,60,80,100,0xe1)
_s("fillp")
_rst()
clip(10,10,50,50)
rectfill(0,0,127,127,8)
clip(40,40,200,200)
circfill(64,64,60,11)
clip(-10,-10,30,30)
rectfill(0,0,127,127,3)
clip()
pset(0,0,7)
_s("clip")
_rst()
camera(-20,15)
rectfill(0,0,30,30,12)
camera(100,100)
circfill(110,110,8,14)
camera(-5.5,3.25)
pset(0,0,7)
camera()
_s("camera")
_rst()
camera(10,10) clip(20,20,60,60) fillp(0x6996)
rectfill(0,0,127,127,0x39)
line(0,0,160,160,7)
_rst()
_s("combo")
"""

CARTS["m_sprites"] = """
-- spr/sspr/palt: multi-cell, flips, up/down/aniso scaling, negative
-- source dims, transparency masks. sheet built deterministically via sset.
_rst()
for y=0,15 do for x=0,31 do sset(x,y,(x*3+y*5)%16) end end
spr(0,10,10) spr(1,30,10) spr(0,50,10,2,2)
spr(0,70,10,1,1,true,false) spr(0,90,10,1,1,false,true) spr(0,110,10,1,1,true,true)
spr(0,-3,30) spr(0,124,30)
_s("spr")
_rst()
sspr(0,0,16,16,10,40,32,32)
sspr(0,0,16,16,50,40,8,8)
sspr(0,0,16,16,70,40,-16,16)
sspr(4,4,8,8,90,40,24,6)
sspr(0,0,32,16,10,90,20,30)
sspr(0,0,16,16,60,90,16,-16)
_s("sspr")
_rst()
palt(0,false) palt(3,true)
spr(0,10,10)
palt(0b1100000000000001)
spr(0,40,10)
palt()
spr(0,70,10)
_s("palt")
"""

CARTS["m_map_tline"] = """
-- map draws (layers via offsets) + tline sweeps incl. negative texture
-- coords (the fixed skip class), negative steps, and the width/height
-- mask + offset registers (0x5f38-0x5f3b).
_rst()
for y=0,15 do for x=0,31 do sset(x,y,(x*7+y*3)%16) end end
for y=0,7 do for x=0,15 do mset(x,y,(x+y*16)%128) end end
map(0,0,5,5,8,4)
map(2,1,60,20,6,6)
map(0,0,-8,90,16,8)
_s("map")
_rst()
tline(0,60,127,60,0,0,0.125,0)
tline(0,70,127,70,2,1,0.25,0.03125)
tline(10,10,120,120,-1,0,0.0625,0.0625)
tline(0,80,127,85,15.5,7.5,-0.125,0)
poke(0x5f38,4) poke(0x5f39,2) poke(0x5f3a,1) poke(0x5f3b,0)
tline(0,100,127,100,0,0,0.5,0)
poke(0x5f38,0) poke(0x5f39,0) poke(0x5f3a,0) poke(0x5f3b,0)
_s("tline")
"""

CARTS["m_pal"] = """
-- palette pipeline: draw palette (mode 0), screen palette incl. the
-- secret colors (mode 1, hashed via the 0x5f10 registers -- the 4bpp
-- framebuffer does not change), table form, direct register pokes.
_rst()
for i=0,15 do rectfill(i*8,0,i*8+7,30,i) end
for i=0,15 do pal(i,(i+3)%16,0) end
for i=0,15 do rectfill(i*8,32,i*8+7,60,i) end
_s("drawpal")
pal()
for i=0,15 do pal(i,143-i,1) end
local h=0
for a=0x5f10,0x5f1f do h=bxor(rotl(h,3),@a) end
_v("screenpal",h)
pal()
_rst()
pal({[0]=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,0},0)
for i=0,15 do rectfill(i*8,64,i*8+7,96,i) end
pal()
_s("paltable")
_rst()
poke(0x5f10,0x8b) poke(0x5f11,140)
local h2=0
for a=0x5f10,0x5f1f do h2=bxor(rotl(h2,3),@a) end
_v("pokescreenpal",h2)
pal()
"""

CARTS["m_print"] = """
-- print: return value (cursor x), cursor registers, control characters
-- composed via chr() (no lexer-dependent escapes -- those live in
-- m_p8scii so a lexer gap cannot mask this cart).
_rst()
local x=print("abc",0,0,7)
_v("curx",x)
print("two\\nlines",0,8,8)
print("a\\tb\\tc",0,24,9)
local y=print("hello",30,40,10)
_v("curx2",y)
print(chr(6).."wWIDE",0,48,11)
print(chr(6).."-w",0,56,12)
print("mix"..chr(9).."tab",0,64,13)
_v("cx",peek(0x5f26)) _v("cy",peek(0x5f27))
_s("print")
"""

CARTS["m_p8scii"] = """
-- P8SCII string escapes written literally (lexer-level conformance --
-- isolated so a parse failure cannot mask other carts).
_rst()
print("\\^wWIDE",0,0,7)
print("\\^tTALL\\^-t\\^-w",0,16,8)
print("\\#5bg",0,40,10)
print("\\fapink",0,56,11)
_s("p8scii")
"""

CARTS["m_math"] = """
-- fix32 math edges: trig, sqrt, mod/intdiv signs, shifts/rotates,
-- overflow wrap, div-by-zero, formatting round-trips.
_v("sin1",sin(0.25)) _v("sin2",sin(-0.7)) _v("cos1",cos(0.1))
_v("atan1",atan2(1,1)) _v("atan2",atan2(-1,0.5)) _v("atan3",atan2(0,0)) _v("atan4",atan2(-0.0001,-1))
_v("sqrt1",sqrt(2)) _v("sqrt2",sqrt(0x7fff)) _v("sqrt3",sqrt(-4)) _v("sqrt4",sqrt(0x0.0001))
_v("mod1",-5%3) _v("mod2",5%-3) _v("mod3",0x7fff.ffff%0.1)
_v("idiv1",-7\\2) _v("idiv2",7\\-2)
_v("shl1",1<<15) _v("shl2",0x0.0001<<31) _v("shl3",1<<32)
_v("shr1",-32768>>4) _v("lshr1",-32768>>>4) _v("shr2",0x1234.5678>>8)
_v("rot1",rotl(0x8000,1)) _v("rot2",rotr(0x0.0001,1)) _v("rot3",rotl(0x1234.5678,16))
_v("ovf1",0x7fff.ffff+0x0.0001) _v("ovf2",-0x8000-1)
_v("div0a",1/0) _v("div0b",-1/0) _v("div0c",0/0)
_v("neg1",-(-32768)) _v("abs1",abs(-32768))
_v("mid1",mid(3,1,2)) _v("sgn0",sgn(0)) _v("max1",max(-0x8000,0x7fff.ffff))
_v("flr1",flr(-3.5)) _v("ceil1",ceil(-3.5)) _v("flr2",flr(0x7fff.8))
_v("tonum1",tonum("0x8000")) _v("tonum2",tonum("1.5"))
local t=tonum("zzz") _v("tonum3",t==nil and "nil" or t)
_v("tostr1",tostr(-32768)) _v("tostr2",tostr(0x0.0001)) _v("tostr3",tostr(1/3))
"""

CARTS["m_memory"] = """
-- memory ops: extended memory (0x8000+, the fixed shorthand class),
-- overlapping memcpy both directions, poke/peek widths, reload.
poke(0x8000,0xab) _v("ext1",@0x8000)
poke4(0x8004,0x1234.5678) _v("ext2",$0x8004)
memset(0x8100,0x5a,64) _v("ext3",$0x8120)
poke(0xcfff,7) _v("ext4",@0xcfff)
for i=0,31 do poke(0x4300+i,(i*7)%256) end
memcpy(0x4310,0x4300,32)
_v("ovl1",$0x4310) _v("ovl2",$0x432c)
memcpy(0x4300,0x4308,16)
_v("ovl3",$0x4300)
_v("p2",peek2(0x4302)) _v("p4",peek4(0x4301))
poke2(0x4340,-1) _v("pk2",$0x4340)
poke(0x0,0xff) reload(0x0,0x0,4) _v("reload1",@0x0)
memset(0x4400,0,8) _v("ms0",$0x4404)
"""

CARTS["m_strings"] = """
-- string API edges: sub negatives/oob/inverted, chr/ord multi,
-- split variants, number-to-string concat formatting, type().
_v("sub1",sub("hello",2,4)) _v("sub2",sub("hello",-3)) _v("sub3",sub("hello",4,99)) _v("sub4",sub("hello",3,2))
_v("chr1",chr(65,66,67)) _v("ord1",ord("abc",2))
local a,b=ord("xyz",1,2) _v("ord2",tostr(a)..","..tostr(b))
local parts=split("a,b,,c") _v("spl1",#parts) _v("spl2",parts[3]=="" and "empty" or parts[3])
local nums=split("1,2,3") _v("spl3",nums[2])
local pp=split("abc","") _v("spl4",pp[2])
_v("cat1","x"..5) _v("cat2","y"..1.5) _v("cat3","z"..-0.0001)
_v("len1",#"hello")
_v("typ1",type(nil)) _v("typ2",type(print)) _v("typ3",type("s")) _v("typ4",type(1.5))
"""

def main():
    for name, body in sorted(CARTS.items()):
        path = os.path.join(HERE, name + ".p8")
        with open(path, "w", encoding="ascii", newline="\n") as f:
            f.write(HEADER)
            f.write(body.lstrip("\n"))
        print(f"wrote {name}.p8")
    print(f"{len(CARTS)} matrix carts generated.")

if __name__ == "__main__":
    main()
